[package]
name = "messages-actix"
version = "0.1.0"
authors = ["Hiroyuki Saito <saito.hiroyuki@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
